---
title: "jgb53d — 3ème année Polytech Marseille - Programmation et analyse de données"
author: "Denis Puthier, Nicolas Terrapon, Arnaud Sergé"
date: "2016-2017"
output: 
  html_document:
    theme: cerulean


---

#### Enseignants

 > - Denis Puthier (DP)
 > - Arnaud Sergé
 > - Nicolas Terrapon
 > - Eugène Christo-Foroux


#### Dataset


| Nom | Lien | Description
-----|------|--------------
| GTF dataset (5k transcripts)  | http://pedagogix-tagc.univ-mrs.fr/courses/jgb53d-bd-prog/practicals/data/hg38_5k.gtf |	An example dataset.

#### Introduction à la bioinformatique

| Nom | Description 
|-----|-----------
|[Bioinformatique: applications dans le contexte de la génomique](http://bit.ly/2ktBWd1)  | Les challenges en bioinformatique dans le domaine de la génomique notamment.


#### Cours Unix

| Nom | Description 
|-----|-----------
| [Vue d'ensemble du système Unix](theorical/bash/unix_course_dp.pdf)| Bash, arborescence, commandes de base, redirections, expressions régulières, réseau, exemple d'outils pour la bioinformatique... 
| [Découvrir le génome humain avec Unix](practicals/01-02_human_genome/human_genome.html) | Quelques statistiques basiques sur le génome humain effectués programmatiquement via le langage Bash
| [Découvrir le génome avec bedtools](practicals/03_bedtools/index.html) | Consolidation des acquis sur les commandes de base. Présentation des commandes Bedtools (sortBed, mergeBed...)


#### Cours Python

**Cours théoriques**

| Nom | Description 
|-----|-----------
| [Premiers pas avec Python](theorical/python/hello_world.html) | Hello world, manipulation de variables.
| [Les tableaux en python](theorical/python/hello_world.html) | Listes, tuples et dictionnaires.
| [Lire et écrire dans un fichier](theorical/python/read_write.html) | la-classe 'file', modes-d'ouverture, fermeture du fichier
| [Les fonctions](theorical/python/functions.html)  | définition et appel, passage d'arguments par noms, variable retour, portée des variables


**Exercices**


| Nom | Description 
|-----|-----------
| [Re-implémentation de la commande cut](practicals/new/cut/cut.html) | Lecture de fichiers, méthodes des objets str, recherche dans l'aide, les listes.
| [Re-implémentation de la commande head](practicals/03_python_2015/head_cmd.html) | Lecture de fichiers,  méthode sur l'objet file, structure conditionnelle, import du module sys, boucle while, boucle for.
| [Implémentation d'une commande count.py](practicals/04_python_2015/count_cmd.html) | Lecture de fichier, boucle for, listes, dictionnaires, module re (regular expression), l'importance du choix des structures de stockage.
| [Implémentation d'un programme tx_len.py](practicals/05_python_2015/tx_len.html) | Lecture de fichier, boucle for, dictionnaires, listes, module re (capture de motif), structure conditionnelles.
| [Implémentation d'un programme nb_exons.py](practicals/06_python_2015/nb_exons.py.html) | Lecture de fichier, boucle for, dictionnaires, listes, module re (capture de motif), structure conditionnelles.
| [Exercice autour des fonctions. Créer des modules](practicals/07_python_2015/functions.html) | Insertion de fonctions dans le code. création d'un module.
| [Créer un programme complet appelant les modules](practicals/08_python_2015/final_program.html) | Importer les modules dans un programme principal. Appeler ces modules. Créer un analyseur d'arguments
| [Calculer la taille des cDNAs](practicals/10_python_2015/cdna_len.html) | Consolider les acquis
| [Extraire une liste de transcripts ou de gènes](practicals/09_python_2015/get_values.html) | Consolider les acquis.
| [An introduction to the grammar of graphics (plotnine)](practicals/intro_ggplot/intro_ggplot.html) | Découvrir le monde des graphiques avec plotnine.
| [Calculer la taille des introns](practicals/introns/introns.html) | Créer un programme complet.

| [Enoncé examen 2014-2015](examen/2014-2015/Examen_2014-2015_Unix_session-1.pdf) | exercice.


#### Récréatif

- Des mots croisés avec des expression régulières ! Voir le site [regexcrossword])(https://regexcrossword.com).
- On s'entraine à coder en Python avec [codewars](https://www.codewars.com/?language=python).
- Une introduction au Shell avec [Datacamp](https://www.datacamp.com/courses/introduction-to-shell-for-data-science).
